import { useEffect, useState } from "react";
import { ArrowRight, TrendingUp, Play, ShieldCheck, Lock, BookOpen, ChevronRight } from "lucide-react";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import ProductPreview from "@/components/ProductPreview";
import PricingPlans from "@/components/PricingPlans";
import { useAuth } from "@/contexts/AuthContext";
import { trackEvent } from "@/lib/analytics";
import { BROKER_STATUS, BROKER_SECURITY_NOTE } from "@/lib/brokers";
import { PST_CHECKOUT_URL, isPlaceholderLink } from "@/lib/checkoutLinks";
const demoScenes = ["journal", "analytics", "review", "process"] as const;
export default function Landing() {
  const { user } = useAuth(); const navigate = useNavigate();
  const [demo, setDemo] = useState(false); const [seconds, setSeconds] = useState(0);
  useEffect(() => { trackEvent("landing_view"); }, []);
  useEffect(() => { if (!demo) return; setSeconds(0); const timer = window.setInterval(() => setSeconds(value => Math.min(45, value + 1)), 1000); return () => clearInterval(timer); }, [demo]);
  if (user) return <Navigate to="/trading" replace />;
  const start = () => { trackEvent("start_free_clicked"); navigate("/auth?signup=1"); };
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-2 px-4 py-4 sm:px-6"><Link to="/welcome" className="flex items-center gap-2 text-sm font-semibold"><TrendingUp className="h-5 w-5 text-primary" />LVL UP</Link><nav className="hidden gap-7 text-xs text-muted-foreground md:flex"><a href="#product">Product</a><a href="#education">PST Education</a><a href="#pricing">Pricing</a></nav><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={() => navigate("/auth")}>Sign in</Button><Button size="sm" onClick={start}>Start Free<ArrowRight /></Button></div></div></header>
    <main>
      <section className="mx-auto max-w-6xl px-4 pb-12 pt-12 text-center sm:px-6 md:pt-16"><p className="section-label">The Trader Performance OS</p><h1 className="mt-5 text-6xl font-semibold sm:text-7xl">LVL UP<span className="text-primary">.</span></h1><h2 className="mx-auto mt-4 max-w-2xl text-3xl leading-tight md:text-4xl">The operating system for disciplined traders.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-muted-foreground sm:text-base">Plan your trades. Sync your execution. Journal your decisions. Measure your edge. Improve your process.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Button size="lg" onClick={start}>Start Free<ArrowRight /></Button><Button size="lg" variant="outline" onClick={() => setDemo(true)}><Play />Watch 45-sec Demo</Button></div><p className="mt-3 text-xs text-muted-foreground">No card required · Your process, not a promise of profit.</p><div className="mx-auto mt-10 max-w-5xl"><ProductPreview /></div></section>
      <section className="premium-band border-b border-border"><div className="mx-auto flex max-w-6xl flex-wrap justify-center gap-x-7 gap-y-3 px-5 py-6 text-xs">{BROKER_STATUS.map(b => <span key={b.name}>{b.name}<span className={`ml-2 text-[10px] ${b.status === "Available" ? "text-primary" : "text-muted-foreground"}`}>{b.status}</span></span>)}{["AI-assisted review", "Trading Journal", "Performance Analytics"].map(text => <span key={text} className="text-muted-foreground">{text}</span>)}</div></section>
      <section className="mx-auto grid max-w-6xl gap-8 px-5 py-20 md:grid-cols-2"><div><p className="section-label">The missing piece</p><h2 className="mt-4 text-3xl leading-tight">You don't need another setup.<br />You need a process.</h2></div><div className="space-y-4 text-sm leading-7 text-muted-foreground"><p>Scattered screenshots. Forgotten decisions. A winning trade that broke your rules. A losing trade that followed them.</p><p>Bring execution and intention into the same workspace. Understand what you actually do, then improve what you can control.</p></div></section>
      <section id="product" className="premium-band"><div className="mx-auto max-w-6xl px-5 py-16"><p className="section-label">One continuous loop</p><div className="mt-7 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{[["Connect", "Bring execution into view. MT5 is available; other connections are clearly marked beta."], ["Journal", "Capture the setup, risk and decision behind every trade."], ["Analyse", "Compare outcomes across strategies, sessions and execution."], ["Improve", "Turn your review into rules, goals and repeatable habits."]].map(([title, body], i) => <div key={title}><p className="font-mono text-xs text-primary">0{i + 1} <ChevronRight className="ml-2 inline h-3 w-3" /></p><h3 className="mt-3 text-xl">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p></div>)}</div></div></section>
      {([{ view: "journal", label: "Execution, with context", title: "Your trading journal. The whole picture.", body: "Entry, stop, target, notes and screenshots together. Revisit trades from your P&L calendar and see the story behind the numbers." }, { view: "analytics", label: "Measure your edge", title: "Evidence over intuition.", body: "Win rate, expectancy, drawdown and strategy performance computed from your own journal. Look for patterns, not guarantees." }, { view: "review", label: "A second set of eyes", title: "AI-assisted trade review.", body: "Analyse structure, execution and performance with a second set of eyes. Educational feedback to question your process, not signals telling you what to buy." }, { view: "process", label: "Discipline is a practice", title: "A better process starts today.", body: "Tie your trader habits, goals and reflections to the decisions you make in the market. Repeat the right actions and review them honestly." }] as const).map((feature, i) => <section key={feature.view} className="premium-band"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-16 lg:grid-cols-2"><div className={i % 2 ? "lg:order-2" : ""}><p className="section-label">{feature.label}</p><h2 className="mt-4 text-3xl leading-tight">{feature.title}</h2><p className="mt-5 max-w-md text-sm leading-7 text-muted-foreground">{feature.body}</p></div><ProductPreview view={feature.view} /></div></section>)}
      <section className="premium-band"><div className="mx-auto max-w-6xl px-5 py-16"><p className="section-label">Broker syncing</p><h2 className="mt-4 text-3xl">Execution meets reflection.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{BROKER_STATUS.map(b => <div key={b.name} className="rounded-lg border border-border bg-card p-5"><h3 className="text-lg">{b.name}</h3><p className={`mt-3 text-xs ${b.status === "Available" ? "text-primary" : "text-muted-foreground"}`}>{b.status}</p></div>)}</div><p className="mt-6 max-w-3xl text-xs leading-6 text-muted-foreground">{BROKER_SECURITY_NOTE}</p></div></section>
      <section id="education" className="premium-band bg-card"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-2"><div><p className="section-label">Separate education program</p><h2 className="mt-4 text-3xl">Precision Structure Trading</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">A 10-module education program with exercises, checklists and chart examples. Develop a structured approach to studying the market.</p><p className="mt-4 text-xs leading-6 text-muted-foreground">PST is not a SaaS tier. Purchasing education does not unlock a LVL UP subscription. Curriculum and course delivery will be confirmed before checkout opens.</p></div><div className="flex flex-col justify-center border-l border-border pl-6"><BookOpen className="h-7 w-7 text-primary" /><p className="mt-5 font-mono text-4xl">$99 <span className="text-sm text-muted-foreground">one-time</span></p><p className="mt-4 text-sm text-muted-foreground">10 modules · Exercises · Checklists · Chart examples</p><Button className="mt-6 self-start" disabled={isPlaceholderLink(PST_CHECKOUT_URL)} onClick={() => { trackEvent("checkout_clicked"); window.open(PST_CHECKOUT_URL, "_blank", "noopener,noreferrer"); }}>PST checkout coming soon<ArrowRight /></Button></div></div></section>
      <section id="pricing" className="premium-band"><div className="mx-auto max-w-6xl px-5 py-16"><div className="mb-9 text-center"><p className="section-label">Invest in your process</p><h2 className="mt-4 text-3xl">Start free. Go deeper when you're ready.</h2><p className="mt-4 text-sm text-muted-foreground">A trading workspace at every level. Existing buyers keep their legacy access.</p></div><PricingPlans /><div className="mt-6 text-center"><Button variant="link" onClick={() => navigate("/auth")}>Already purchased? Sign in to redeem your license.</Button></div></div></section>
      <section className="premium-band"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 md:grid-cols-3"><div><ShieldCheck className="h-6 w-6 text-primary" /><h3 className="mt-4 text-lg">Your journal stays yours.</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Account-scoped data access. Private trade screenshots use expiring signed links.</p></div><div><Lock className="h-6 w-6 text-primary" /><h3 className="mt-4 text-lg">Built for review, not execution.</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">LVL UP does not submit orders. Use read-only credentials where your broker supports them.</p></div><div><BookOpen className="h-6 w-6 text-primary" /><h3 className="mt-4 text-lg">No profit promises.</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Analytics and AI are educational tools, not financial advice. Trading involves risk of loss.</p></div></div></section>
      <section id="faq" className="premium-band"><div className="mx-auto max-w-3xl px-5 py-16"><p className="section-label">Questions, answered</p><h2 className="mt-4 text-3xl">Before you get started.</h2><div className="mt-8">{[["What can I use for free?", "Habits, goals, up to 10 manual trades, trade notes, the P&L calendar and basic analytics. Existing trials continue until their original end date."], ["Which brokers are supported?", "MT5 is available. TradeLocker and Match-Trader are beta and require statement checks. cTrader is coming soon and cannot be connected yet."], ["Does AI give trading signals?", "No. AI-assisted review offers educational observations about structure, execution and risk. Verify its output and make your own decisions."], ["What happens to my existing plan?", "Legacy memberships and purchased licenses retain their existing entitlements. They are identified as Legacy in your account; historical data is preserved."], ["How do payments work?", "Whop is the primary checkout, with Gumroad as an alternative. Checkout remains unavailable until real product links and purchase verification are configured."], ["Is PST included in my subscription?", "No. Precision Structure Trading is a separate $99 education program, not lifetime SaaS access." ]].map(([q, a]) => <details key={q} className="border-b border-border py-5"><summary className="cursor-pointer text-sm font-medium">{q}</summary><p className="mt-3 text-sm leading-7 text-muted-foreground">{a}</p></details>)}</div></div></section>
      <section className="premium-band"><div className="mx-auto max-w-6xl px-5 py-20 text-center"><p className="section-label">The next trade deserves a process</p><h2 className="mt-4 text-3xl md:text-4xl">Trade with intention. Review with clarity.</h2><Button size="lg" className="mt-7" onClick={start}>Start Free<ArrowRight /></Button></div></section>
    </main><footer className="border-t border-border"><div className="mx-auto flex max-w-6xl flex-wrap justify-between gap-4 px-5 py-7 text-xs text-muted-foreground"><span>© {new Date().getFullYear()} LVL UP — The Trader Performance OS</span><span>Educational tools. Not financial advice.</span></div></footer>
    <Dialog open={demo} onOpenChange={setDemo}><DialogContent className="max-h-[90dvh] w-[calc(100%-2rem)] max-w-4xl overflow-y-auto"><DialogTitle>LVL UP · 45-second product walkthrough</DialogTitle><DialogDescription>Illustrative workspace · no customer results or live account data.</DialogDescription><ProductPreview view={demoScenes[Math.min(3, Math.floor(seconds / 12))]} /><div className="flex items-center justify-between text-xs text-muted-foreground"><span>{["Journal your execution", "Measure performance", "Review the decision", "Improve your process"][Math.min(3, Math.floor(seconds / 12))]}</span><span className="font-mono">{seconds}s / 45s</span></div><progress className="h-1 w-full accent-primary" value={seconds} max={45} />{seconds === 45 && <Button onClick={() => setSeconds(0)}><Play />Replay demo</Button>}</DialogContent></Dialog>
  </div>;
}
